# Generated by Django 5.0.7 on 2025-01-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotdetailsmodel',
            old_name='mouja_name',
            new_name='plot_no',
        ),
        migrations.RemoveField(
            model_name='plotdetailsmodel',
            name='khatiyan_document',
        ),
        migrations.RemoveField(
            model_name='plotdetailsmodel',
            name='khatiyan_receipt',
        ),
        migrations.RemoveField(
            model_name='plotdetailsmodel',
            name='trace_map',
        ),
        migrations.RemoveField(
            model_name='plotdetailsmodel',
            name='village_map',
        ),
    ]
