# Generated by Django 5.0.7 on 2025-01-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_alter_purchaserdetailsmodel_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plot_booking_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.plotbookingdetailsmodel', verbose_name='')),
            ],
            options={
                'db_table': 'tbl_earning',
            },
        ),
    ]
