# Generated by Django 5.0.7 on 2025-01-25 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_earningmodel_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningmodel',
            name='earning_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='WithdrawModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.membermodel', verbose_name='')),
            ],
            options={
                'db_table': 'tbl_withdrawal',
            },
        ),
    ]
