# Generated by Django 5.0.7 on 2025-01-27 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_alter_earningmodel_earning_amount_withdrawmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reward', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.membermodel', verbose_name='')),
            ],
        ),
    ]
