# Generated by Django 5.0.7 on 2025-01-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_rewardmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rewardmodel',
            table='tbl_reward',
        ),
    ]
